### ISSUE TITLE
Is it possible to run ColBERT on a regular PC?

### ISSUE THREAD

**Issue by gigagiova** [stanford-futuredata/ColBERT#151]
I have tried to execute locally the _intro.ipynb_ notebook many times, and each time I received an error message during the indexing phase. They usually come in the form of: `RuntimeError: CUDA error: CUBLAS_STATUS_NOT_INITIALIZED when calling cublasCreate(handle)` or similar errors that signal an OOM problem.

I have tried reducing the collection size from 260k to just 20, but to no avail. Is there anything else I can try? If not, what are the minimum requirements to run ColBERT? For reference, I have a GeForce GTX 1050 and 8G of free memory.

Thanks in advance

**Comment by okhat** [comment]
Thanks for the detailed description @gigagiova. I have no experience with attempting this. I can say that ColBERT works just fine with 12GB GPUs like Titan V and others. It also works fine on Google Colab.

Maybe you can attempt this on Colab?

**Comment by gigagiova** [comment]
I have previously tried Colab, but it got stuck during indexing with this output:

```
#> Starting...
#> Starting...
#> Starting...
#> Starting...
```

Am I missing something? Could the problem be that I wasn't running it in a Conda env?

**Comment by okhat** [comment]
That might be it. Also, set nranks=1 (not 4) for Colab and for your 1050. The code there is launching 4 processes, but you have a single GPU

**Comment by gigagiova** [comment]
Thanks, that fixed it! I should have noticed.

When trying to run the notebook, a new problem arose in the function:

```
    def _prepare_lookup(self, pids):
        if isinstance(pids, list):
            pids = torch.tensor(pids)

        assert pids.dim() == 1

        if self.use_gpu:
            pids = pids.cuda()
            self.lengths = self.lengths.cuda()    # No effects
        pids = pids.long()
        lengths = self.lengths[pids]
        if self.use_gpu:
            lengths = lengths.cuda()
        offsets = self.offsets[pids]

        return pids, lengths, offsets
```

It is caused by the fact that `self.lengths` is in the CPU and `pids` is in the GPU. I have tried moving `self.lengths` to the GPU, but it seems to be stuck in the CPU, and vice-versa (even though CUDA works otherwise). 

What can be causing this problem? Thanks again

**Comment by santhnm2** [comment]
This was fixed by #149, just pushed yesterday

**Comment by gigagiova** [comment]
Now everything works as expected. Thanks!
